### ISSUE TITLE
Navigation is a bit confusing

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/taskly#11]
Once you are inside a project, it is a bit confusing when you click on "Completed" since it pushes a page into the pagestack and shows the back button. How about using the header.sections and having two sections shown in every project page "Upcoming | Completed"? This way the only header action shown would be search task, delete project, rename project which are genuine actions while "Upcoming" and "Completed" are more like filters.

**Comment by iBelieve** [comment]
Thanks for the suggestion of using tabs, that was something I hadn't considered but worked out really well!
